### ISSUE TITLE
Can I please be added back to UASAL?

### ISSUE THREAD

**Issue by biancalondra** [uasal/spacehardwarehandbook-public#9]
I had to reset my 2 factor authentication which triggered GitHub to remove me from UASAL (I can't access any private repos) and delete my forked repos. 

Can I please be re-added to the organization?

<img width="400" alt="github-removed" src="https://github.com/user-attachments/assets/a8d90007-f618-427d-8dd4-27ac35b96ebb">

Apologies if this is not the right space to address this, but it seemed the most relevant repo of the ones I have access to.

**Comment by sfrinaldi** [comment]
@douglase @patrickingraham Just noticed this issue which looks like it would be either of you for re-adding them.

**Comment by douglase** [comment]
try now

**Comment by biancalondra** [comment]
back in now, thanks!
